srcs/Kqueue.cpp
srcs/Kqueue.hpp
srcs/Makefile
srcs/main.cpp

mainの処理でkqueueの箇所を分離して、コンフィグファイルから読み込んだポート番号を使って待機できるように変更

separate kqueue process from main

---

srcs/http/httpParser.cpp
srcs/http/httpParser.hpp
srcs/http/httpReq.cpp
srcs/http/httpReq.hpp

ざっくりとhttpParserの概観を下書きしました。コンパイルはしていません。細かいエラー処理などもいれていません。
まずrequest line(GET / HTTP/1.1的な奴)をparseし、その後空行が来るまで各ヘッダーフィールドをparseしていき、空行の後にbodyを読み込む流れになっています。

[draft] rough overview of http parser

---

srcs/Client.cpp
srcs/Client.hpp
srcs/Makefile
srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp
srcs/main.cpp

Client用意＆RequestResponseの準備

---

srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp
srcs/http/httpReq.cpp
srcs/http/httpReq.hpp

simple POST DELETE method

---

srcs/http/httpReq.cpp
srcs/http/httpReq.hpp

httpリクエストのパース段階でチェックしたいいくつかのフォーマットエラーの暫定的な処理を追加しました

[WIP] check some http request format

---

srcs/conf/Location.cpp
srcs/conf/Location.hpp
srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp
srcs/http/httpReq.cpp
srcs/http/httpReq.hpp
srcs/main.cpp

[WIP] add base delete's function

---

srcs/conf/valid_test/tmp.conf
srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp

再起的に潜ってディレクトリとその中身を削除する関数の下書きです。現状階層を潜っての全削除は出来ますが、パーミッションがないものも削除できてしまっています。またrootやpath周りがまだ不十分です。

[WIP] request DELETE directory

---

srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp
srcs/http/httpReq.cpp

auto_index_handlerの草案です。
取り敢えずindex ofがブラウザで表示できるようになっていますが、index directiveとの兼ね合いで少し修正しなければならない箇所が残っています。
また、redirectの時に変更を加えたkeep_alive周りが上手く機能していなかったので修正しました。

[add] auto_index_handler, but needs to be fixed a little more

---

srcs/http/HttpRes.cpp

[fix] case of response status error when an index-type directive exists in config

---

srcs/Kqueue.cpp
srcs/Socket.cpp
srcs/conf/Location.cpp
srcs/conf/configParser.cpp
srcs/conf/virtualServer.cpp
srcs/http/HttpRes.cpp
srcs/http/cgi.cpp
srcs/http/httpReq.cpp
srcs/main.cpp

[clean] output logs

---

srcs/http/HttpRes.cpp
srcs/http/HttpRes.hpp

headerの送信とdelete時のエラーハンドリングの一部を追加しました

Draft delete dir

---

srcs/http/HttpRes.cpp

画像を送信できるようにする

---

srcs/http/HttpRes.cpp

レスポンスで返せるmedia-typesをいくつか追加しました。

[add] media-types that can be sent in response

---

srcs/http/HttpRes.cpp

autoindexやindexディレクティブが有効な際のpathが正しくなるように修正しました。
aliasが機能するように修正しました。

[fix] around index and alias

---

srcs/conf/configParser.cpp
srcs/http/HttpRes.cpp
srcs/http/httpReq.cpp

[add] handle HEAD method

---

srcs/http/HttpRes.cpp

open()関数をaccess()関数とofstreamで置き換えました。

Replace function

---

srcs/Kqueue.cpp
srcs/Kqueue.hpp
srcs/Socket.cpp
srcs/conf/configParser.cpp
srcs/http/HttpRes.cpp
srcs/http/cgi.cpp
srcs/http/cgi.hpp
srcs/main.cpp

エラー処理がされていなかった箇所にエラー処理を追加しました。
まだ一部処理を書いていない箇所があります。

Handle errors

---

srcs/Socket.cpp
srcs/Socket.hpp
srcs/main.cpp

socketをnewで宣言していた箇所を修正し、leakを修正しました

[fix] memory leak

---

srcs/http/HttpRes.cpp

ステータスコード200の時にbodyがなかった場合204をセットするようにしました。

[add] NO_CONTENT status

---

srcs/http/httpReq.cpp

チャンクの終端判定とidxを進め忘れていた箇所を修正しました。

[fix] end of chunk determination

---

srcs/http/cgi.cpp

SCRIPT_NAMEとconfigのlocationディレクティブの重複を解消しました。

[fix] joinPath in cgi

---

srcs/http/HttpRes.cpp
srcs/http/cgi.cpp
srcs/http/cgi.hpp

waitpidをどう扱うのが良いか、まだ定まっていない状態です。

[WIP] handle child processes

---

srcs/http/HttpReq.cpp
srcs/http/HttpReq.hpp

parseSchemeの修正をしました。absUrlParseはまだ機能しません。

absUrlParse周り

---

srcs/http/HttpRes.cpp

stat失敗時にsb変数に関する処理をしないように修正しました。

handlePost内のstatに関する修正

---

srcs/EventLoop.cpp
srcs/Kqueue.cpp

kqueue改善ラスト
